spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://livk.com:3306/security_demo?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: livk.com
    password: 123456
  application:
    name: feign-provider-biz
  cloud:
    nacos:
      discovery:
        server-addr: livk.com:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9661
